# Generated by Django 3.2.3 on 2021-05-16 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('total_units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FetchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('units_sold', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sales_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='database.sku')),
            ],
        ),
    ]
