# Generated by Django 3.2.3 on 2021-05-16 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FetchData',
            new_name='SkuData',
        ),
    ]
