# Generated by Django 3.2.3 on 2021-05-16 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_fetchdata_skudata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='sku_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skudata',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
