# Generated by Django 3.2.3 on 2021-05-16 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20210516_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='skudata',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skudata',
            name='size',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skudata',
            name='units_sold',
            field=models.IntegerField(),
        ),
    ]
